version: "3"

networks:
  web:
    external: true
  internal:
    external: false

services:
  db:
    image: lscr.io/linuxserver/mariadb:latest
    networks:
      - internal
    labels:
      - traefik.enable=false
    restart: unless-stopped
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    container_name: wp_db_mikaleb_back

  blog:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_HOST: db
    labels:
      - traefik.http.routers.blog.rule=Host(`back.mikaleb.com`)
      - traefik.http.routers.blog.tls=true
      - traefik.http.routers.blog.tls.certresolver=lets-encrypt
      - traefik.port=80
    networks:
      - internal
      - web
    depends_on:
      - db


